### PR TITLE
Add/Remove Dates When Publishing/Unpublishing

### PR DESCRIPTION
**Pull request by ashmaroli**
I don't have access to push to your `master` branch. So opening a PR (and yeah, things are going to be tricky)
See how you're listed as a co-author of the commit.

**Do not merge this PR**

### CODE REVIEW

**Comment by gavinhoward** [comment]
Okay, merged.

**Comment by ashmaroli** [comment]
It said **`do not merge`**

**Comment by gavinhoward** [comment]
Oh dang. I am sick right now, so I am not thinking straight.

Let me see what I can do.

**Comment by ashmaroli** [comment]
`git reset` helped :+1:

**Comment by gavinhoward** [comment]
Good. Sorry. Can you tell me what I should do now?

**Comment by ashmaroli** [comment]
I did not intend to make the process so complicated for you..
But since you're fine with not getting credited, everything's sorted.. :+1: 

Now, the ball is in our (the maintainers') court.. We shall review your changes and leave comments / approve as usual on GitHub projects..

**Comment by gavinhoward** [comment]
Sounds good.

**Pull request merged**
